name: CI

on:
  schedule:
    - cron: '*/25 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "Markf349g"
          git config user.email "mark.vizzhachiy@gmail.com"

      - name: Update AUTOFILE and commit
        run: |
          date -u +'%Y-%m-%d %H:%M:%S' >> AUTOFILE
          git add AUTOFILE
          git commit -m "Automated Update" || echo "Nothing to commit"

      - name: Push changes
        run: |
          git push origin HEAD:main

      - name: Clean up if committed
        run: |
          git diff --cached --exit-code || rm -f AUTOFILE
